/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as protectedSettingsIndexRouteImport } from './routes/(protected)/settings/index'
import { Route as protectedPaymentsIndexRouteImport } from './routes/(protected)/payments/index'
import { Route as protectedInvoicesIndexRouteImport } from './routes/(protected)/invoices/index'
import { Route as protectedDashboardIndexRouteImport } from './routes/(protected)/dashboard/index'
import { Route as protectedClientsIndexRouteImport } from './routes/(protected)/clients/index'
import { Route as protectedAnalyticsIndexRouteImport } from './routes/(protected)/analytics/index'
import { Route as publicAuthVerifyEmailRouteImport } from './routes/(public)/auth/verify-email'
import { Route as publicAuthRegisterRouteImport } from './routes/(public)/auth/register'
import { Route as publicAuthLoginRouteImport } from './routes/(public)/auth/login'
import { Route as protectedInvoicesInvoiceIdRouteRouteImport } from './routes/(protected)/invoices/$invoiceId/route'
import { Route as publicAuthForgotPasswordIndexRouteImport } from './routes/(public)/auth/forgot-password/index'
import { Route as publicAuthForgotPasswordVerifyRouteImport } from './routes/(public)/auth/forgot-password/verify'
import { Route as publicAuthForgotPasswordResetRouteImport } from './routes/(public)/auth/forgot-password/reset'
import { Route as protectedInvoicesInvoiceIdEditRouteImport } from './routes/(protected)/invoices/$invoiceId/edit'
import { Route as protectedInvoicesInvoiceIdDetailsRouteImport } from './routes/(protected)/invoices/$invoiceId/details'

const protectedInvoicesNewLazyRouteImport = createFileRoute(
  '/(protected)/invoices/new',
)()

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const protectedSettingsIndexRoute = protectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedPaymentsIndexRoute = protectedPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedInvoicesIndexRoute = protectedInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedDashboardIndexRoute = protectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedClientsIndexRoute = protectedClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedAnalyticsIndexRoute = protectedAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedInvoicesNewLazyRoute = protectedInvoicesNewLazyRouteImport
  .update({
    id: '/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => protectedRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(protected)/invoices/new.lazy').then((d) => d.Route),
  )
const publicAuthVerifyEmailRoute = publicAuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicAuthRegisterRoute = publicAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicAuthLoginRoute = publicAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => publicRouteRoute,
} as any)
const protectedInvoicesInvoiceIdRouteRoute =
  protectedInvoicesInvoiceIdRouteRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const publicAuthForgotPasswordIndexRoute =
  publicAuthForgotPasswordIndexRouteImport.update({
    id: '/auth/forgot-password/',
    path: '/auth/forgot-password/',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicAuthForgotPasswordVerifyRoute =
  publicAuthForgotPasswordVerifyRouteImport.update({
    id: '/auth/forgot-password/verify',
    path: '/auth/forgot-password/verify',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicAuthForgotPasswordResetRoute =
  publicAuthForgotPasswordResetRouteImport.update({
    id: '/auth/forgot-password/reset',
    path: '/auth/forgot-password/reset',
    getParentRoute: () => publicRouteRoute,
  } as any)
const protectedInvoicesInvoiceIdEditRoute =
  protectedInvoicesInvoiceIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => protectedInvoicesInvoiceIdRouteRoute,
  } as any)
const protectedInvoicesInvoiceIdDetailsRoute =
  protectedInvoicesInvoiceIdDetailsRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => protectedInvoicesInvoiceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/invoices/$invoiceId': typeof protectedInvoicesInvoiceIdRouteRouteWithChildren
  '/auth/login': typeof publicAuthLoginRoute
  '/auth/register': typeof publicAuthRegisterRoute
  '/auth/verify-email': typeof publicAuthVerifyEmailRoute
  '/invoices/new': typeof protectedInvoicesNewLazyRoute
  '/analytics/': typeof protectedAnalyticsIndexRoute
  '/clients/': typeof protectedClientsIndexRoute
  '/dashboard/': typeof protectedDashboardIndexRoute
  '/invoices/': typeof protectedInvoicesIndexRoute
  '/payments/': typeof protectedPaymentsIndexRoute
  '/settings/': typeof protectedSettingsIndexRoute
  '/invoices/$invoiceId/details': typeof protectedInvoicesInvoiceIdDetailsRoute
  '/invoices/$invoiceId/edit': typeof protectedInvoicesInvoiceIdEditRoute
  '/auth/forgot-password/reset': typeof publicAuthForgotPasswordResetRoute
  '/auth/forgot-password/verify': typeof publicAuthForgotPasswordVerifyRoute
  '/auth/forgot-password/': typeof publicAuthForgotPasswordIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/invoices/$invoiceId': typeof protectedInvoicesInvoiceIdRouteRouteWithChildren
  '/auth/login': typeof publicAuthLoginRoute
  '/auth/register': typeof publicAuthRegisterRoute
  '/auth/verify-email': typeof publicAuthVerifyEmailRoute
  '/invoices/new': typeof protectedInvoicesNewLazyRoute
  '/analytics': typeof protectedAnalyticsIndexRoute
  '/clients': typeof protectedClientsIndexRoute
  '/dashboard': typeof protectedDashboardIndexRoute
  '/invoices': typeof protectedInvoicesIndexRoute
  '/payments': typeof protectedPaymentsIndexRoute
  '/settings': typeof protectedSettingsIndexRoute
  '/invoices/$invoiceId/details': typeof protectedInvoicesInvoiceIdDetailsRoute
  '/invoices/$invoiceId/edit': typeof protectedInvoicesInvoiceIdEditRoute
  '/auth/forgot-password/reset': typeof publicAuthForgotPasswordResetRoute
  '/auth/forgot-password/verify': typeof publicAuthForgotPasswordVerifyRoute
  '/auth/forgot-password': typeof publicAuthForgotPasswordIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(protected)/invoices/$invoiceId': typeof protectedInvoicesInvoiceIdRouteRouteWithChildren
  '/(public)/auth/login': typeof publicAuthLoginRoute
  '/(public)/auth/register': typeof publicAuthRegisterRoute
  '/(public)/auth/verify-email': typeof publicAuthVerifyEmailRoute
  '/(protected)/invoices/new': typeof protectedInvoicesNewLazyRoute
  '/(protected)/analytics/': typeof protectedAnalyticsIndexRoute
  '/(protected)/clients/': typeof protectedClientsIndexRoute
  '/(protected)/dashboard/': typeof protectedDashboardIndexRoute
  '/(protected)/invoices/': typeof protectedInvoicesIndexRoute
  '/(protected)/payments/': typeof protectedPaymentsIndexRoute
  '/(protected)/settings/': typeof protectedSettingsIndexRoute
  '/(protected)/invoices/$invoiceId/details': typeof protectedInvoicesInvoiceIdDetailsRoute
  '/(protected)/invoices/$invoiceId/edit': typeof protectedInvoicesInvoiceIdEditRoute
  '/(public)/auth/forgot-password/reset': typeof publicAuthForgotPasswordResetRoute
  '/(public)/auth/forgot-password/verify': typeof publicAuthForgotPasswordVerifyRoute
  '/(public)/auth/forgot-password/': typeof publicAuthForgotPasswordIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invoices/$invoiceId'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
    | '/invoices/new'
    | '/analytics/'
    | '/clients/'
    | '/dashboard/'
    | '/invoices/'
    | '/payments/'
    | '/settings/'
    | '/invoices/$invoiceId/details'
    | '/invoices/$invoiceId/edit'
    | '/auth/forgot-password/reset'
    | '/auth/forgot-password/verify'
    | '/auth/forgot-password/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invoices/$invoiceId'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
    | '/invoices/new'
    | '/analytics'
    | '/clients'
    | '/dashboard'
    | '/invoices'
    | '/payments'
    | '/settings'
    | '/invoices/$invoiceId/details'
    | '/invoices/$invoiceId/edit'
    | '/auth/forgot-password/reset'
    | '/auth/forgot-password/verify'
    | '/auth/forgot-password'
  id:
    | '__root__'
    | '/(protected)'
    | '/(public)'
    | '/(public)/'
    | '/(protected)/invoices/$invoiceId'
    | '/(public)/auth/login'
    | '/(public)/auth/register'
    | '/(public)/auth/verify-email'
    | '/(protected)/invoices/new'
    | '/(protected)/analytics/'
    | '/(protected)/clients/'
    | '/(protected)/dashboard/'
    | '/(protected)/invoices/'
    | '/(protected)/payments/'
    | '/(protected)/settings/'
    | '/(protected)/invoices/$invoiceId/details'
    | '/(protected)/invoices/$invoiceId/edit'
    | '/(public)/auth/forgot-password/reset'
    | '/(public)/auth/forgot-password/verify'
    | '/(public)/auth/forgot-password/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(protected)/settings/': {
      id: '/(protected)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof protectedSettingsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/payments/': {
      id: '/(protected)/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof protectedPaymentsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/invoices/': {
      id: '/(protected)/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof protectedInvoicesIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard/': {
      id: '/(protected)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof protectedDashboardIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/clients/': {
      id: '/(protected)/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof protectedClientsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/analytics/': {
      id: '/(protected)/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof protectedAnalyticsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/invoices/new': {
      id: '/(protected)/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof protectedInvoicesNewLazyRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(public)/auth/verify-email': {
      id: '/(public)/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof publicAuthVerifyEmailRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/auth/register': {
      id: '/(public)/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof publicAuthRegisterRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/auth/login': {
      id: '/(public)/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof publicAuthLoginRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(protected)/invoices/$invoiceId': {
      id: '/(protected)/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof protectedInvoicesInvoiceIdRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(public)/auth/forgot-password/': {
      id: '/(public)/auth/forgot-password/'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password/'
      preLoaderRoute: typeof publicAuthForgotPasswordIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/auth/forgot-password/verify': {
      id: '/(public)/auth/forgot-password/verify'
      path: '/auth/forgot-password/verify'
      fullPath: '/auth/forgot-password/verify'
      preLoaderRoute: typeof publicAuthForgotPasswordVerifyRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/auth/forgot-password/reset': {
      id: '/(public)/auth/forgot-password/reset'
      path: '/auth/forgot-password/reset'
      fullPath: '/auth/forgot-password/reset'
      preLoaderRoute: typeof publicAuthForgotPasswordResetRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(protected)/invoices/$invoiceId/edit': {
      id: '/(protected)/invoices/$invoiceId/edit'
      path: '/edit'
      fullPath: '/invoices/$invoiceId/edit'
      preLoaderRoute: typeof protectedInvoicesInvoiceIdEditRouteImport
      parentRoute: typeof protectedInvoicesInvoiceIdRouteRoute
    }
    '/(protected)/invoices/$invoiceId/details': {
      id: '/(protected)/invoices/$invoiceId/details'
      path: '/details'
      fullPath: '/invoices/$invoiceId/details'
      preLoaderRoute: typeof protectedInvoicesInvoiceIdDetailsRouteImport
      parentRoute: typeof protectedInvoicesInvoiceIdRouteRoute
    }
  }
}

interface protectedInvoicesInvoiceIdRouteRouteChildren {
  protectedInvoicesInvoiceIdDetailsRoute: typeof protectedInvoicesInvoiceIdDetailsRoute
  protectedInvoicesInvoiceIdEditRoute: typeof protectedInvoicesInvoiceIdEditRoute
}

const protectedInvoicesInvoiceIdRouteRouteChildren: protectedInvoicesInvoiceIdRouteRouteChildren =
  {
    protectedInvoicesInvoiceIdDetailsRoute:
      protectedInvoicesInvoiceIdDetailsRoute,
    protectedInvoicesInvoiceIdEditRoute: protectedInvoicesInvoiceIdEditRoute,
  }

const protectedInvoicesInvoiceIdRouteRouteWithChildren =
  protectedInvoicesInvoiceIdRouteRoute._addFileChildren(
    protectedInvoicesInvoiceIdRouteRouteChildren,
  )

interface protectedRouteRouteChildren {
  protectedInvoicesInvoiceIdRouteRoute: typeof protectedInvoicesInvoiceIdRouteRouteWithChildren
  protectedInvoicesNewLazyRoute: typeof protectedInvoicesNewLazyRoute
  protectedAnalyticsIndexRoute: typeof protectedAnalyticsIndexRoute
  protectedClientsIndexRoute: typeof protectedClientsIndexRoute
  protectedDashboardIndexRoute: typeof protectedDashboardIndexRoute
  protectedInvoicesIndexRoute: typeof protectedInvoicesIndexRoute
  protectedPaymentsIndexRoute: typeof protectedPaymentsIndexRoute
  protectedSettingsIndexRoute: typeof protectedSettingsIndexRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedInvoicesInvoiceIdRouteRoute:
    protectedInvoicesInvoiceIdRouteRouteWithChildren,
  protectedInvoicesNewLazyRoute: protectedInvoicesNewLazyRoute,
  protectedAnalyticsIndexRoute: protectedAnalyticsIndexRoute,
  protectedClientsIndexRoute: protectedClientsIndexRoute,
  protectedDashboardIndexRoute: protectedDashboardIndexRoute,
  protectedInvoicesIndexRoute: protectedInvoicesIndexRoute,
  protectedPaymentsIndexRoute: protectedPaymentsIndexRoute,
  protectedSettingsIndexRoute: protectedSettingsIndexRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicAuthLoginRoute: typeof publicAuthLoginRoute
  publicAuthRegisterRoute: typeof publicAuthRegisterRoute
  publicAuthVerifyEmailRoute: typeof publicAuthVerifyEmailRoute
  publicAuthForgotPasswordResetRoute: typeof publicAuthForgotPasswordResetRoute
  publicAuthForgotPasswordVerifyRoute: typeof publicAuthForgotPasswordVerifyRoute
  publicAuthForgotPasswordIndexRoute: typeof publicAuthForgotPasswordIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicAuthLoginRoute: publicAuthLoginRoute,
  publicAuthRegisterRoute: publicAuthRegisterRoute,
  publicAuthVerifyEmailRoute: publicAuthVerifyEmailRoute,
  publicAuthForgotPasswordResetRoute: publicAuthForgotPasswordResetRoute,
  publicAuthForgotPasswordVerifyRoute: publicAuthForgotPasswordVerifyRoute,
  publicAuthForgotPasswordIndexRoute: publicAuthForgotPasswordIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedRouteRoute: protectedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
