/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as protectedSettingsIndexRouteImport } from './routes/(protected)/settings/index'
import { Route as protectedPaymentsIndexRouteImport } from './routes/(protected)/payments/index'
import { Route as protectedInvoicesIndexRouteImport } from './routes/(protected)/invoices/index'
import { Route as protectedDashboardIndexRouteImport } from './routes/(protected)/dashboard/index'
import { Route as protectedClientsIndexRouteImport } from './routes/(protected)/clients/index'
import { Route as protectedAnalyticsIndexRouteImport } from './routes/(protected)/analytics/index'
import { Route as protectedInvoicesInvoiceIdRouteImport } from './routes/(protected)/invoices/$invoiceId'
import { Route as publicAuthVerifyEmailIndexRouteImport } from './routes/(public)/auth/verify-email/index'
import { Route as publicAuthRegisterIndexRouteImport } from './routes/(public)/auth/register/index'
import { Route as publicAuthLoginIndexRouteImport } from './routes/(public)/auth/login/index'

const protectedInvoicesNewLazyRouteImport = createFileRoute(
  '/(protected)/invoices/new',
)()

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const protectedSettingsIndexRoute = protectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedPaymentsIndexRoute = protectedPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedInvoicesIndexRoute = protectedInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedDashboardIndexRoute = protectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedClientsIndexRoute = protectedClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedAnalyticsIndexRoute = protectedAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedInvoicesNewLazyRoute = protectedInvoicesNewLazyRouteImport
  .update({
    id: '/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => protectedRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(protected)/invoices/new.lazy').then((d) => d.Route),
  )
const protectedInvoicesInvoiceIdRoute =
  protectedInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const publicAuthVerifyEmailIndexRoute =
  publicAuthVerifyEmailIndexRouteImport.update({
    id: '/auth/verify-email/',
    path: '/auth/verify-email/',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicAuthRegisterIndexRoute = publicAuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicAuthLoginIndexRoute = publicAuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => publicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/invoices/$invoiceId': typeof protectedInvoicesInvoiceIdRoute
  '/invoices/new': typeof protectedInvoicesNewLazyRoute
  '/analytics/': typeof protectedAnalyticsIndexRoute
  '/clients/': typeof protectedClientsIndexRoute
  '/dashboard/': typeof protectedDashboardIndexRoute
  '/invoices/': typeof protectedInvoicesIndexRoute
  '/payments/': typeof protectedPaymentsIndexRoute
  '/settings/': typeof protectedSettingsIndexRoute
  '/auth/login/': typeof publicAuthLoginIndexRoute
  '/auth/register/': typeof publicAuthRegisterIndexRoute
  '/auth/verify-email/': typeof publicAuthVerifyEmailIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/invoices/$invoiceId': typeof protectedInvoicesInvoiceIdRoute
  '/invoices/new': typeof protectedInvoicesNewLazyRoute
  '/analytics': typeof protectedAnalyticsIndexRoute
  '/clients': typeof protectedClientsIndexRoute
  '/dashboard': typeof protectedDashboardIndexRoute
  '/invoices': typeof protectedInvoicesIndexRoute
  '/payments': typeof protectedPaymentsIndexRoute
  '/settings': typeof protectedSettingsIndexRoute
  '/auth/login': typeof publicAuthLoginIndexRoute
  '/auth/register': typeof publicAuthRegisterIndexRoute
  '/auth/verify-email': typeof publicAuthVerifyEmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(protected)/invoices/$invoiceId': typeof protectedInvoicesInvoiceIdRoute
  '/(protected)/invoices/new': typeof protectedInvoicesNewLazyRoute
  '/(protected)/analytics/': typeof protectedAnalyticsIndexRoute
  '/(protected)/clients/': typeof protectedClientsIndexRoute
  '/(protected)/dashboard/': typeof protectedDashboardIndexRoute
  '/(protected)/invoices/': typeof protectedInvoicesIndexRoute
  '/(protected)/payments/': typeof protectedPaymentsIndexRoute
  '/(protected)/settings/': typeof protectedSettingsIndexRoute
  '/(public)/auth/login/': typeof publicAuthLoginIndexRoute
  '/(public)/auth/register/': typeof publicAuthRegisterIndexRoute
  '/(public)/auth/verify-email/': typeof publicAuthVerifyEmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/analytics/'
    | '/clients/'
    | '/dashboard/'
    | '/invoices/'
    | '/payments/'
    | '/settings/'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/verify-email/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/analytics'
    | '/clients'
    | '/dashboard'
    | '/invoices'
    | '/payments'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
  id:
    | '__root__'
    | '/(protected)'
    | '/(public)'
    | '/(public)/'
    | '/(protected)/invoices/$invoiceId'
    | '/(protected)/invoices/new'
    | '/(protected)/analytics/'
    | '/(protected)/clients/'
    | '/(protected)/dashboard/'
    | '/(protected)/invoices/'
    | '/(protected)/payments/'
    | '/(protected)/settings/'
    | '/(public)/auth/login/'
    | '/(public)/auth/register/'
    | '/(public)/auth/verify-email/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(protected)/settings/': {
      id: '/(protected)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof protectedSettingsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/payments/': {
      id: '/(protected)/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof protectedPaymentsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/invoices/': {
      id: '/(protected)/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof protectedInvoicesIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard/': {
      id: '/(protected)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof protectedDashboardIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/clients/': {
      id: '/(protected)/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof protectedClientsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/analytics/': {
      id: '/(protected)/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof protectedAnalyticsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/invoices/new': {
      id: '/(protected)/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof protectedInvoicesNewLazyRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/invoices/$invoiceId': {
      id: '/(protected)/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof protectedInvoicesInvoiceIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(public)/auth/verify-email/': {
      id: '/(public)/auth/verify-email/'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email/'
      preLoaderRoute: typeof publicAuthVerifyEmailIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/auth/register/': {
      id: '/(public)/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof publicAuthRegisterIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/auth/login/': {
      id: '/(public)/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof publicAuthLoginIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
  }
}

interface protectedRouteRouteChildren {
  protectedInvoicesInvoiceIdRoute: typeof protectedInvoicesInvoiceIdRoute
  protectedInvoicesNewLazyRoute: typeof protectedInvoicesNewLazyRoute
  protectedAnalyticsIndexRoute: typeof protectedAnalyticsIndexRoute
  protectedClientsIndexRoute: typeof protectedClientsIndexRoute
  protectedDashboardIndexRoute: typeof protectedDashboardIndexRoute
  protectedInvoicesIndexRoute: typeof protectedInvoicesIndexRoute
  protectedPaymentsIndexRoute: typeof protectedPaymentsIndexRoute
  protectedSettingsIndexRoute: typeof protectedSettingsIndexRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedInvoicesInvoiceIdRoute: protectedInvoicesInvoiceIdRoute,
  protectedInvoicesNewLazyRoute: protectedInvoicesNewLazyRoute,
  protectedAnalyticsIndexRoute: protectedAnalyticsIndexRoute,
  protectedClientsIndexRoute: protectedClientsIndexRoute,
  protectedDashboardIndexRoute: protectedDashboardIndexRoute,
  protectedInvoicesIndexRoute: protectedInvoicesIndexRoute,
  protectedPaymentsIndexRoute: protectedPaymentsIndexRoute,
  protectedSettingsIndexRoute: protectedSettingsIndexRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicAuthLoginIndexRoute: typeof publicAuthLoginIndexRoute
  publicAuthRegisterIndexRoute: typeof publicAuthRegisterIndexRoute
  publicAuthVerifyEmailIndexRoute: typeof publicAuthVerifyEmailIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicAuthLoginIndexRoute: publicAuthLoginIndexRoute,
  publicAuthRegisterIndexRoute: publicAuthRegisterIndexRoute,
  publicAuthVerifyEmailIndexRoute: publicAuthVerifyEmailIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedRouteRoute: protectedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
