/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as protectedDashboardIndexRouteImport } from './routes/(protected)/dashboard/index'
import { Route as protectedClientsIndexRouteImport } from './routes/(protected)/clients/index'
import { Route as publicAuthVerifyEmailIndexRouteImport } from './routes/(public)/auth/verify-email/index'
import { Route as publicAuthRegisterIndexRouteImport } from './routes/(public)/auth/register/index'
import { Route as publicAuthLoginIndexRouteImport } from './routes/(public)/auth/login/index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const protectedDashboardIndexRoute = protectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedClientsIndexRoute = protectedClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const publicAuthVerifyEmailIndexRoute =
  publicAuthVerifyEmailIndexRouteImport.update({
    id: '/auth/verify-email/',
    path: '/auth/verify-email/',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicAuthRegisterIndexRoute = publicAuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicAuthLoginIndexRoute = publicAuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => publicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/clients/': typeof protectedClientsIndexRoute
  '/dashboard/': typeof protectedDashboardIndexRoute
  '/auth/login/': typeof publicAuthLoginIndexRoute
  '/auth/register/': typeof publicAuthRegisterIndexRoute
  '/auth/verify-email/': typeof publicAuthVerifyEmailIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/clients': typeof protectedClientsIndexRoute
  '/dashboard': typeof protectedDashboardIndexRoute
  '/auth/login': typeof publicAuthLoginIndexRoute
  '/auth/register': typeof publicAuthRegisterIndexRoute
  '/auth/verify-email': typeof publicAuthVerifyEmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(protected)/clients/': typeof protectedClientsIndexRoute
  '/(protected)/dashboard/': typeof protectedDashboardIndexRoute
  '/(public)/auth/login/': typeof publicAuthLoginIndexRoute
  '/(public)/auth/register/': typeof publicAuthRegisterIndexRoute
  '/(public)/auth/verify-email/': typeof publicAuthVerifyEmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients/'
    | '/dashboard/'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/verify-email/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
  id:
    | '__root__'
    | '/(protected)'
    | '/(public)'
    | '/(public)/'
    | '/(protected)/clients/'
    | '/(protected)/dashboard/'
    | '/(public)/auth/login/'
    | '/(public)/auth/register/'
    | '/(public)/auth/verify-email/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(protected)/dashboard/': {
      id: '/(protected)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof protectedDashboardIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/clients/': {
      id: '/(protected)/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof protectedClientsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(public)/auth/verify-email/': {
      id: '/(public)/auth/verify-email/'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email/'
      preLoaderRoute: typeof publicAuthVerifyEmailIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/auth/register/': {
      id: '/(public)/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof publicAuthRegisterIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/auth/login/': {
      id: '/(public)/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof publicAuthLoginIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
  }
}

interface protectedRouteRouteChildren {
  protectedClientsIndexRoute: typeof protectedClientsIndexRoute
  protectedDashboardIndexRoute: typeof protectedDashboardIndexRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedClientsIndexRoute: protectedClientsIndexRoute,
  protectedDashboardIndexRoute: protectedDashboardIndexRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicAuthLoginIndexRoute: typeof publicAuthLoginIndexRoute
  publicAuthRegisterIndexRoute: typeof publicAuthRegisterIndexRoute
  publicAuthVerifyEmailIndexRoute: typeof publicAuthVerifyEmailIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicAuthLoginIndexRoute: publicAuthLoginIndexRoute,
  publicAuthRegisterIndexRoute: publicAuthRegisterIndexRoute,
  publicAuthVerifyEmailIndexRoute: publicAuthVerifyEmailIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedRouteRoute: protectedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
